name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Build and Artifact Upload
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
        DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
      run: |
        echo 'Docker Login'
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_KEY
        echo 'Running Dcoker Image Build...'
        docker image build -t $DOCKERHUB_REPO .
        echo 'Pushing Docker Image...'
        docker image push $DOCKERHUB_REPO
        echo 'Done...'
