name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare Sonar Scanner CLI
      env:
        SONAR_SCANNER_VERSION: 4.2.0.1873
      run: |
        sudo apt-get install -y nodejs
        wget -q -O sonar-scanner-cli-linux.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip
        unzip sonar-scanner-cli-linux.zip
        rm sonar-scanner-cli-linux.zip
        sudo mv sonar-scanner-${SONAR_SCANNER_VERSION}-linux /opt/sonar-scanner
        sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/bin/sonar-scanner

    - uses: actions/checkout@v2

    - name: Run Sonar Scanner
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN

    - name: Run Build and Artifact Upload
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
        DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
      run: |
        echo 'Docker Login'
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_KEY
        echo 'Running Dcoker Image Build...'
        docker image build -t $DOCKERHUB_REPO .
        echo 'Pushing Docker Image...'
        docker image push $DOCKERHUB_REPO
        echo 'Done...'
